"""add push tokens and notify message preview

Revision ID: 0a20271f0831
Revises: 95f274877edb
Create Date: 2026-06-21 20:38:29.540682
"""
from alembic import op
import sqlalchemy as sa


revision = '0a20271f0831'
down_revision = '95f274877edb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    # server_default needed here (unlike a fresh column with no NOT NULL
    # constraint) so existing rows get a value instead of failing the
    # NOT NULL check; matches the model's default=False.
    op.add_column(
        'users',
        sa.Column('notify_message_preview', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_message_preview')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    # ### end Alembic commands ###
