"""add matches, video_sessions, auth/discovery fields

Revision ID: 7cfa661ceae4
Revises: a027a715f0b5
Create Date: 2026-06-17 14:53:33.179984
"""
from alembic import op
import sqlalchemy as sa


revision = '7cfa661ceae4'
down_revision = 'a027a715f0b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_a_id', sa.Uuid(), nullable=False),
    sa.Column('user_b_id', sa.Uuid(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'video', 'met', 'closed', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_a_id <> user_b_id', name='ck_match_distinct_users'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('room_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_sessions')
    op.drop_table('matches')
    # ### end Alembic commands ###
