"""add avatar_url to users

Revision ID: 95f274877edb
Revises: e398c1873a03
Create Date: 2026-06-21 16:08:18.069979
"""
from alembic import op
import sqlalchemy as sa


revision = '95f274877edb'
down_revision = 'e398c1873a03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
