"""add blocks and reports

Revision ID: ca015febfffb
Revises: 7cfa661ceae4
Create Date: 2026-06-20 13:49:18.484404
"""
from alembic import op
import sqlalchemy as sa


revision = 'ca015febfffb'
down_revision = '7cfa661ceae4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blocker_id <> blocked_id', name='ck_block_distinct_users'),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_block_pair')
    )
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('reported_user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Enum('inappropriate_behavior', 'fake_profile', 'harassment', 'safety_concern', 'other', name='reportreason'), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('open', 'reviewed', 'actioned', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reporter_id <> reported_user_id', name='ck_report_distinct_users'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('blocks')
    # ### end Alembic commands ###
