"""add ratings table

Revision ID: dddbb438c6f3
Revises: ca015febfffb
Create Date: 2026-06-20 21:29:10.450009
"""
from alembic import op
import sqlalchemy as sa


revision = 'dddbb438c6f3'
down_revision = 'ca015febfffb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('rater_id', sa.Uuid(), nullable=False),
    sa.Column('rated_user_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rater_id <> rated_user_id', name='ck_rating_distinct_users'),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_rating_score_range'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rated_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'rater_id', name='uq_rating_per_match_rater')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    # ### end Alembic commands ###
